name: Node JS Testing

# Controls when the workflow will run
# Tells script when it will run
on:
  # Triggers the workflow when a new commit is made <OR> PR on main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Tells script what to do
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # hosted by Github
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # when GitHub Action is running, name is displayed
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up node to run for action
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install npm dependencies
      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
          # Name/Value is pulled from Github > Settings > Secrets and Variables > Actions
        run: npm test
          
